### ISSUE TITLE
500 Internal Server Error when trying to get devices

### ISSUE THREAD

**Issue by justaniles** [petersulucz/smarthome#2]
The ridiculously long and obscure stack trace says something about "Device with name already exists." This should not be so.

**Comment by petersulucz** [comment]
no repro. must be user error.

**Comment by justaniles** [comment]
Definitely **not** user error. Issue still exists

**Comment by justaniles** [comment]
![image](https://cloud.githubusercontent.com/assets/13080292/17317057/90978c14-582e-11e6-82c6-926eddf57131.png)

Case. In. Point.

**Comment by petersulucz** [comment]
This was user error.

**Comment by petersulucz** [comment]
Closing.

**Comment by petersulucz** [comment]
because the user was not doing anything correctly
