### ISSUE TITLE
WHAT IS THIS SHIT

### ISSUE THREAD

**Issue by justaniles** [petersulucz/smarthome#4]
NEED TO CREATE A USER WITH PASSWORD LESS THAN 8 CHARACTERS.

WHAT ABOUT MY '0000' PASSWORDS?! HUH?!? **THINK ABOUT THE USER**

**Comment by petersulucz** [comment]
FINE FINE. OK FINE. KEEPING 8 CHARACTER MIN. BUT ALLOWING '0000' AS VALID
