### ISSUE TITLE
Can't execute LIFX device function

### ISSUE THREAD

**Issue by justaniles** [petersulucz/smarthome#5]
Dis janx broke during a demo. Customers are rioting

![image](https://cloud.githubusercontent.com/assets/13080292/17653083/63374574-6243-11e6-98a3-6c6b822e39d4.png)

> "{"Message":"An error has occurred.","ExceptionMessage":"The type initializer for 'HomeHub.Adapters.Lifx.FunctionHandlers.Handlers' threw an exception.","ExceptionType":"System.TypeInitializationException","StackTrace":"   at HomeHub.Adapters.Lifx.FunctionHandlers.Handlers.ExecuteFunction(UserContext context, LifxMetaData meta, DeviceFunction function, Object argument)\r\n   at HomeHub.Adapters.Lifx.LifxAdapter.ExecuteFunction(UserContext context, DeviceImport deviceData, DeviceFunction function, Object argument)\r\n   at HomeHub.Service.Common.Data.DeviceManager.<ExecuteAction>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at HomeHub.Service.Web.Controllers.DeviceController.<Execute>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at HomeHub.Service.Web.Pipeline.Filters.RequireCredentialsAttribute.<ExecuteAuthorizationFilterAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Method not found: 'Void HomeHub.Common.Trace.HomeHubEventSource.MethodEnter()'.","ExceptionType":"System.MissingMethodException","StackTrace":"   at HomeHub.Adapters.Lifx.FunctionHandlers.Handlers..cctor()"}}"

**Comment by petersulucz** [comment]
MEF error. recompiled. Closing as user error
